spring.application.name=Apisena

spring.datasource.url=jdbc:mysql://localhost:3307/dbpedidos?serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=1234

#Configuracion JPA/Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
server.port=8090

jwt.secret.key= 3d09a2e4795c74ef0a83c1bec69e34e052adf93f9fcbcf347e7bb021903fbc7e
jwt.expiration.time=86400000
