spring.application.name=Apisena

spring.datasource.url=jdbc:mysql://localhost:3306/dbpedidos?serverTimezone=America/Bogota
spring.datasource.username=root
spring.datasource.password=1312

#Configuracion JPA/Hibernate

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
server.port=8090
jwt.secret.key=ff7d17145f65caa8d73ae20fe6e728441a935ac06f0b195a9af1c219f4a46df6
jwt.expiration.time=86400000
#JWT secret key generator